language: cpp

jobs:
  include:

    - &linter-stage
      stage: Linter + Doxygen + non-debug Ubuntu/gcc-5 test
      env: NAME="CPP-LINT"
      install:
      script: scripts/travis_lint.sh
      before_cache:

    - stage: Linter + Doxygen + non-debug Ubuntu/gcc-5 test
      env: NAME="DOXYGEN-CHECK"
      addons:
        apt:
          packages:
            - doxygen
      install:
      script: scripts/travis_doxygen.sh
      before_cache:

    # Ubuntu Linux with glibc using g++-5
    - stage: Linter + Doxygen + non-debug Ubuntu/gcc-5 test
      os: linux
      sudo: false
      compiler: gcc
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
            - libubsan0
      before_install:
        - mkdir bin ; ln -s /usr/bin/gcc-5 bin/gcc
      # env: COMPILER=g++-5 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover -fno-omit-frame-pointer"
      env: COMPILER="ccache g++-5"

    # OS X using g++
    - stage: Test different OS/CXX/Flags
      os: osx
      sudo: false
      compiler: gcc
      cache: ccache
      before_install:
          #we create symlink to non-ccache gcc, to be used in tests
        - mkdir bin ; ln -s /usr/bin/gcc bin/gcc
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
        - export PATH=/usr/local/opt/ccache/libexec:$PATH
      env: COMPILER="ccache g++"

    # OS X using clang++
    - stage: Test different OS/CXX/Flags
      os: osx
      sudo: false
      compiler: clang
      cache: ccache
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
        - export PATH=/usr/local/opt/ccache/libexec:$PATH
      env:
        - COMPILER="ccache clang++ -Qunused-arguments -fcolor-diagnostics"
        - CCACHE_CPP2=yes

    # Ubuntu Linux with glibc using g++-5, debug mode
    - stage: Test different OS/CXX/Flags
      os: linux
      sudo: false
      compiler: gcc
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
            - libubsan0
      before_install:
        - mkdir bin ; ln -s /usr/bin/gcc-5 bin/gcc
      # env: COMPILER=g++-5 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover -fno-omit-frame-pointer"
      env:
        - COMPILER="ccache g++-5"
        - EXTRA_CXXFLAGS="-DDEBUG"
      script: echo "Not running any tests for a debug build."

    # Ubuntu Linux with glibc using clang++-3.7
    - stage: Test different OS/CXX/Flags
      os: linux
      sudo: false
      compiler: clang
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libwww-perl
            - clang-3.7
            - libstdc++-5-dev
            - libubsan0
      before_install:
        - mkdir bin ; ln -s /usr/bin/clang-3.7 bin/gcc
        - export CCACHE_CPP2=yes
      # env: COMPILER=clang++-3.7 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined,integer -fno-omit-frame-pointer"
      env:
        - COMPILER="ccache clang++-3.7 -Qunused-arguments -fcolor-diagnostics"
        - CCACHE_CPP2=yes

    # Ubuntu Linux with glibc using clang++-3.7, debug mode
    - stage: Test different OS/CXX/Flags
      os: linux
      sudo: false
      compiler: clang
      cache: ccache
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libwww-perl
            - clang-3.7
            - libstdc++-5-dev
            - libubsan0
      before_install:
        - mkdir bin ; ln -s /usr/bin/clang-3.7 bin/gcc
        - export CCACHE_CPP2=yes
      # env: COMPILER=clang++-3.7 SAN_FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined,integer -fno-omit-frame-pointer"
      env:
        - COMPILER="ccache clang++-3.7 -Qunused-arguments -fcolor-diagnostics"
        - CCACHE_CPP2=yes
        - EXTRA_CXXFLAGS="-DDEBUG"
      script: echo "Not running any tests for a debug build."

  allow_failures:
    - <<: *linter-stage

install:
  - ccache --max-size=1G
  - make -C src minisat2-download
  - make -C src/ansi-c library_check
  - make -C src "CXX=${COMPILER}" "CXXFLAGS=-Wall -Werror -pedantic -O2 -g ${EXTRA_CXXFLAGS}" -j2
  - make -C src "CXX=${COMPILER}" "CXXFLAGS=-Wall -Werror -pedantic -O2 -g ${EXTRA_CXXFLAGS}" -j2 clobber.dir memory-models.dir musketeer.dir

script:
  - if [ -e bin/gcc ] ; then export PATH=$PWD/bin:$PATH ; fi ;
  - env UBSAN_OPTIONS=print_stacktrace=1 make -C regression test "CXX=${COMPILER}" "CXXFLAGS=-Wall -Werror -pedantic -O2 -g ${EXTRA_CXXFLAGS}"
  - make -C unit "CXX=${COMPILER}" "CXXFLAGS=-Wall -Werror -pedantic -O2 -g ${EXTRA_CXXFLAGS}" -j2
  - make -C unit test

before_cache:
  - ccache -s
