version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y g++-5 flex bison make git libwww-perl patch
  build:
    commands:
      - echo Build started on `date`
      - (cd src ; make minisat2-download)
      - (cd src ; make -j2)
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
